<?php

declare(strict_types=1);

namespace AndreighioC\IngWebPay\Console;

use AndreighioC\IngWebPay\Events\PaymentFailed;
use AndreighioC\IngWebPay\Events\PaymentSuccessful;
use AndreighioC\IngWebPay\Facades\IngWebPay;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class SyncPendingOrdersCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'ingwebpay:sync {order_id* : The order ID(s) generated by ING WebPay.}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Manually check and sync the status of pending transactions from ING WebPay.';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $orderIds = $this->argument('order_id');

        foreach ($orderIds as $orderId) {
            $this->info("Checking status for order ID: {$orderId}...");

            try {
                $status = IngWebPay::getOrderStatusExtended((string)$orderId);

                if ($status->isSuccessful()) {
                    $this->info("✅ Order {$orderId} is SUCCESSFUL.");
                    event(new PaymentSuccessful($status, (string)$orderId));
                } elseif ($status->isFailed()) {
                    $this->error("❌ Order {$orderId} has FAILED/DECLINED.");
                    event(new PaymentFailed($status, (string)$orderId));
                } else {
                    $this->warn("⏳ Order {$orderId} is still pending/unresolved. Status: {$status->actionCodeDescription}");
                }
            } catch (\Exception $e) {
                $this->error("🚨 Failed to check order {$orderId}: " . $e->getMessage());
                Log::error("ingwebpay:sync failed for {$orderId}", ['exception' => $e->getMessage()]);
            }

            $this->line('---');
        }

        $this->info('Sync completed!');

        return self::SUCCESS;
    }
}
